// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(func, seconds, minutes, hours) {
    var interval, last;
    if (seconds == null) {
      seconds = 0;
    }
    if (minutes == null) {
      minutes = 0;
    }
    if (hours == null) {
      hours = 0;
    }
    interval = seconds + (minutes * 60) + (hours * 60 * 60);
    last = void 0;
    return function() {
      var delta, now;
      if (last == null) {
        last = Date.now();
        return func.apply(this, arguments);
      }
      now = Date.now();
      delta = now - last;
      last = now;
      if (delta < interval) {
        return;
      }
      return func.apply(this, arguments);
    };
  };

}).call(this);

//# sourceMappingURL=index.js.map
