// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(func, seconds, minutes, hours) {
    var last;
    if (seconds == null) {
      seconds = 0;
    }
    if (minutes == null) {
      minutes = 0;
    }
    if (hours == null) {
      hours = 0;
    }
    last = Date.now();
    return function() {
      var delta, now;
      now = Date.now();
      delta = now - last;
      if (delta < seconds) {
        return;
      }
      last = now;
      return func.apply(func, arguments);
    };
  };

}).call(this);

//# sourceMappingURL=index.js.map
